# Generated by Django 5.1.2 on 2024-10-14 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('capacity', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('venue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venue.venue')),
            ],
        ),
    ]
